
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 11;
  public static final int AND = 21;
  public static final int LT = 13;
  public static final int ELSE = 5;
  public static final int TRUTH = 33;
  public static final int PLUS = 9;
  public static final int RBRACE = 30;
  public static final int RPAREN = 26;
  public static final int OR = 20;
  public static final int INT = 3;
  public static final int LTE = 14;
  public static final int SEMI = 23;
  public static final int WHILE = 8;
  public static final int BITNOT = 19;
  public static final int RETURN = 7;
  public static final int ERROR = 34;
  public static final int IF = 6;
  public static final int LBRACE = 29;
  public static final int LBRACKET = 27;
  public static final int LPAREN = 25;
  public static final int GT = 15;
  public static final int ID = 31;
  public static final int GTE = 16;
  public static final int RBRACKET = 28;
  public static final int NUM = 32;
  public static final int COMMA = 24;
  public static final int EOF = 0;
  public static final int DIVIDE = 12;
  public static final int MINUS = 10;
  public static final int error = 1;
  public static final int ASSIGN = 22;
  public static final int EQ = 17;
  public static final int BOOL = 2;
  public static final int NEQ = 18;
  public static final int VOID = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BOOL",
  "INT",
  "VOID",
  "ELSE",
  "IF",
  "RETURN",
  "WHILE",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "LT",
  "LTE",
  "GT",
  "GTE",
  "EQ",
  "NEQ",
  "BITNOT",
  "OR",
  "AND",
  "ASSIGN",
  "SEMI",
  "COMMA",
  "LPAREN",
  "RPAREN",
  "LBRACKET",
  "RBRACKET",
  "LBRACE",
  "RBRACE",
  "ID",
  "NUM",
  "TRUTH",
  "ERROR"
  };
}

